language: java
jdk:
  - oraclejdk8
  
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true#sudo: false
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer
#script:
#  - jdk_switcher use oraclejdk8
  
